#!/bin/sh -eu
$DOCKER build --cache-from $IMAGE_BASE:$TARGET-build --target build -t $IMAGE_BASE:$TARGET-build .
$DOCKER build --cache-from $IMAGE_BASE:$TARGET-target --target target -t $IMAGE_BASE:$TARGET-target .
$DOCKER build --cache-from $IMAGE_BASE:$TARGET -t $IMAGE_BASE:$TARGET .
