name: Build

on:
  push:
    branches:
      - master

env:
  REGISTRY: docker.io
  IMAGE_NAME: vtavernier/cross

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Fetch cache
        run: |
          for TARGET in $(cd targets && echo *); do
            docker pull $REGISTRY/$IMAGE_NAME:$TARGET-build || true
            docker pull $REGISTRY/$IMAGE_NAME:$TARGET-target || true
            docker pull $REGISTRY/$IMAGE_NAME:$TARGET || true
          done

      - name: Build the images
        run: make images

      - name: Test the images
        run: make test

      - name: Push Docker images
        run: make push
