name: Build image

on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
        description: Image name
    secrets:
      DOCKER_USERNAME:
        description: Docker username
        required: true
      DOCKER_PASSWORD:
        description: Docker password
        required: true

env:
  REGISTRY: docker.io
  IMAGE_NAME: vtavernier/cross

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Free up some space from the distribution
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/share/swift

      - name: Build the image
        run: make docker-image-${{ inputs.image }}

      - name: Test the image
        run: make test-${{ inputs.image }}

      - name: Push the image
        run: make push-${{ inputs.image }}
