name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/build-image.yml

    strategy:
      fail-fast: false
      matrix:
        image:
          - raspberrypi-bookworm
          - raspberrypi-bullseye
          - x86_64-bullseye

    with:
      image: ${{ matrix.image }}

    permissions:
      contents: read
      packages: write
