name: Build image

on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
        description: Image name

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/cross

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Free up some space from the distribution
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/share/swift

      - name: Build the image
        run: make docker-image-${{ inputs.image }}

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@8befa3d6491e023b3676c07bf71a1680700e3e6e

      - name: Install cross
        run: cargo binstall --no-confirm cross@=0.2.5

      - name: Test the image
        run: make test-${{ inputs.image }}

      - name: Push the image
        run: make push-${{ inputs.image }}
