name: Build

on:
  push:
    branches:
      - master

env:
  REGISTRY: docker.io
  IMAGE_NAME: vtavernier/cross

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Free up some space from the distribution
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/share/swift

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build the images
        run: make images

      - name: Test the images
        run: make test

      - name: Push Docker images
        run: make push
