name: Debug

on:
  push:
    branches:
      - ci

env:
  REGISTRY: docker.io
  IMAGE_NAME: vtavernier/cross

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: mxschmitt/action-tmate@v3
